
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Test03 {

    private static final boolean T = true;
    private static final boolean F = false;

    public static void main(String[] args) {
        List<Cetrta.Celica> celice = new ArrayList<>(Arrays.asList(
            new Cetrta.Celica(8, 5),
            new Cetrta.Celica(1, 7),
            new Cetrta.Celica(2, 6),
            new Cetrta.Celica(11, 11),
            new Cetrta.Celica(7, 7),
            new Cetrta.Celica(8, 12),
            new Cetrta.Celica(9, 1),
            new Cetrta.Celica(1, 12),
            new Cetrta.Celica(6, 6),
            new Cetrta.Celica(7, 8),
            new Cetrta.Celica(2, 0),
            new Cetrta.Celica(10, 6),
            new Cetrta.Celica(6, 8),
            new Cetrta.Celica(3, 0),
            new Cetrta.Celica(4, 10),
            new Cetrta.Celica(11, 8),
            new Cetrta.Celica(11, 9),
            new Cetrta.Celica(8, 10),
            new Cetrta.Celica(8, 6),
            new Cetrta.Celica(8, 7),
            new Cetrta.Celica(6, 11),
            new Cetrta.Celica(1, 8),
            new Cetrta.Celica(9, 9),
            new Cetrta.Celica(12, 6),
            new Cetrta.Celica(1, 4),
            new Cetrta.Celica(0, 12),
            new Cetrta.Celica(6, 2),
            new Cetrta.Celica(0, 2),
            new Cetrta.Celica(5, 9),
            new Cetrta.Celica(12, 10),
            new Cetrta.Celica(7, 10),
            new Cetrta.Celica(6, 1),
            new Cetrta.Celica(0, 11),
            new Cetrta.Celica(5, 8),
            new Cetrta.Celica(9, 8),
            new Cetrta.Celica(7, 11),
            new Cetrta.Celica(8, 3),
            new Cetrta.Celica(12, 8),
            new Cetrta.Celica(5, 6),
            new Cetrta.Celica(7, 9),
            new Cetrta.Celica(8, 8),
            new Cetrta.Celica(4, 11),
            new Cetrta.Celica(2, 2),
            new Cetrta.Celica(1, 5),
            new Cetrta.Celica(1, 2),
            new Cetrta.Celica(10, 2),
            new Cetrta.Celica(6, 5),
            new Cetrta.Celica(12, 7),
            new Cetrta.Celica(5, 12),
            new Cetrta.Celica(1, 1),
            new Cetrta.Celica(5, 0),
            new Cetrta.Celica(4, 0),
            new Cetrta.Celica(12, 3),
            new Cetrta.Celica(8, 0),
            new Cetrta.Celica(0, 5),
            new Cetrta.Celica(0, 8),
            new Cetrta.Celica(1, 0),
            new Cetrta.Celica(0, 7),
            new Cetrta.Celica(5, 2),
            new Cetrta.Celica(3, 2),
            new Cetrta.Celica(10, 5),
            new Cetrta.Celica(11, 10),
            new Cetrta.Celica(11, 4),
            new Cetrta.Celica(11, 3),
            new Cetrta.Celica(6, 3),
            new Cetrta.Celica(12, 4),
            new Cetrta.Celica(10, 4),
            new Cetrta.Celica(2, 12),
            new Cetrta.Celica(2, 9),
            new Cetrta.Celica(10, 11),
            new Cetrta.Celica(7, 1),
            new Cetrta.Celica(8, 11),
            new Cetrta.Celica(3, 10),
            new Cetrta.Celica(12, 9),
            new Cetrta.Celica(1, 10),
            new Cetrta.Celica(4, 9),
            new Cetrta.Celica(0, 10),
            new Cetrta.Celica(4, 6),
            new Cetrta.Celica(4, 3),
            new Cetrta.Celica(1, 9),
            new Cetrta.Celica(4, 7),
            new Cetrta.Celica(10, 0),
            new Cetrta.Celica(12, 2),
            new Cetrta.Celica(3, 11),
            new Cetrta.Celica(7, 2),
            new Cetrta.Celica(10, 1),
            new Cetrta.Celica(2, 5),
            new Cetrta.Celica(5, 11),
            new Cetrta.Celica(4, 4),
            new Cetrta.Celica(7, 6),
            new Cetrta.Celica(3, 3),
            new Cetrta.Celica(5, 3),
            new Cetrta.Celica(0, 4),
            new Cetrta.Celica(10, 12),
            new Cetrta.Celica(7, 4),
            new Cetrta.Celica(11, 1),
            new Cetrta.Celica(11, 6),
            new Cetrta.Celica(1, 11),
            new Cetrta.Celica(3, 7),
            new Cetrta.Celica(10, 10)
        ));
        celice.sort(null);
        System.out.println(celice);
    }
}
