
import java.util.*;

public class Test10 {

    public static void main(String[] args) {

        Tretja.Dogodek[] dogodki = {
            new Tretja.SluzbenaPot(37, new Cas(0, 10), true),
            new Tretja.SluzbenaPot(18, new Cas(0, 15), true),
            new Tretja.SluzbenaPot(29, new Cas(0, 18), true),
            new Tretja.Malica(48, new Cas(0, 19), true),
            new Tretja.Rekreacija(3, new Cas(0, 21), true),
            new Tretja.SluzbenaPot(46, new Cas(0, 22), true),
            new Tretja.SluzbenaPot(1, new Cas(0, 23), true),
            new Tretja.Rekreacija(43, new Cas(0, 32), true),
            new Tretja.Malica(28, new Cas(0, 34), true),
            new Tretja.SluzbenaPot(24, new Cas(0, 40), true),
            new Tretja.Rekreacija(15, new Cas(0, 42), true),
            new Tretja.SluzbenaPot(38, new Cas(0, 44), true),
            new Tretja.Rekreacija(0, new Cas(0, 50), true),
            new Tretja.Rekreacija(5, new Cas(0, 51), true),
            new Tretja.Rekreacija(25, new Cas(0, 52), true),
            new Tretja.Malica(10, new Cas(0, 52), true),
            new Tretja.Rekreacija(42, new Cas(0, 54), true),
            new Tretja.Rekreacija(49, new Cas(0, 54), true),
            new Tretja.Rekreacija(6, new Cas(0, 59), true),
            new Tretja.Rekreacija(0, new Cas(1, 7), false),
            new Tretja.SluzbenaPot(38, new Cas(1, 16), false),
            new Tretja.SluzbenaPot(24, new Cas(1, 16), false),
            new Tretja.Malica(34, new Cas(1, 18), true),
            new Tretja.SluzbenaPot(4, new Cas(1, 24), true),
            new Tretja.Rekreacija(0, new Cas(1, 25), true),
            new Tretja.Rekreacija(38, new Cas(1, 35), true),
            new Tretja.Rekreacija(49, new Cas(1, 35), false),
            new Tretja.Malica(35, new Cas(1, 40), true),
            new Tretja.Malica(33, new Cas(1, 41), true),
            new Tretja.Rekreacija(8, new Cas(1, 43), true),
            new Tretja.Rekreacija(11, new Cas(1, 45), true),
            new Tretja.Malica(7, new Cas(1, 58), true),
            new Tretja.Malica(21, new Cas(2, 2), true),
            new Tretja.SluzbenaPot(40, new Cas(2, 5), true),
            new Tretja.Malica(32, new Cas(2, 7), true),
            new Tretja.SluzbenaPot(30, new Cas(2, 16), true),
            new Tretja.SluzbenaPot(24, new Cas(2, 18), true),
            new Tretja.SluzbenaPot(30, new Cas(2, 21), false),
            new Tretja.Rekreacija(9, new Cas(2, 24), true),
            new Tretja.SluzbenaPot(13, new Cas(2, 25), true),
            new Tretja.Rekreacija(22, new Cas(2, 25), true),
            new Tretja.Malica(34, new Cas(2, 27), false),
            new Tretja.Rekreacija(3, new Cas(2, 28), false),
            new Tretja.Rekreacija(36, new Cas(2, 31), true),
            new Tretja.SluzbenaPot(30, new Cas(2, 36), true),
            new Tretja.Malica(48, new Cas(2, 39), false),
            new Tretja.SluzbenaPot(20, new Cas(2, 45), true),
            new Tretja.SluzbenaPot(26, new Cas(2, 47), true),
            new Tretja.Rekreacija(43, new Cas(2, 48), false),
            new Tretja.Malica(17, new Cas(2, 51), true),
            new Tretja.SluzbenaPot(39, new Cas(2, 52), true),
            new Tretja.Malica(12, new Cas(2, 54), true),
            new Tretja.Rekreacija(11, new Cas(2, 55), false),
            new Tretja.SluzbenaPot(31, new Cas(2, 56), true),
            new Tretja.Malica(27, new Cas(2, 57), true),
            new Tretja.SluzbenaPot(34, new Cas(2, 57), true),
            new Tretja.Malica(28, new Cas(3, 7), false),
            new Tretja.Rekreacija(45, new Cas(3, 12), true),
            new Tretja.SluzbenaPot(14, new Cas(3, 17), true),
            new Tretja.SluzbenaPot(48, new Cas(3, 25), true),
            new Tretja.Rekreacija(41, new Cas(3, 27), true),
            new Tretja.Rekreacija(22, new Cas(3, 29), false),
            new Tretja.Rekreacija(2, new Cas(3, 32), true),
            new Tretja.Malica(16, new Cas(3, 32), true),
            new Tretja.Rekreacija(2, new Cas(3, 39), false),
            new Tretja.Rekreacija(23, new Cas(3, 39), true),
            new Tretja.Rekreacija(47, new Cas(3, 43), true),
            new Tretja.Rekreacija(25, new Cas(3, 50), false),
            new Tretja.SluzbenaPot(3, new Cas(3, 55), true),
            new Tretja.SluzbenaPot(25, new Cas(3, 55), true),
            new Tretja.SluzbenaPot(46, new Cas(3, 57), false),
            new Tretja.Rekreacija(49, new Cas(4, 0), true),
            new Tretja.SluzbenaPot(39, new Cas(4, 2), false),
            new Tretja.SluzbenaPot(18, new Cas(4, 4), false),
            new Tretja.Malica(43, new Cas(4, 5), true),
            new Tretja.Malica(21, new Cas(4, 5), false),
            new Tretja.SluzbenaPot(19, new Cas(4, 7), true),
            new Tretja.SluzbenaPot(24, new Cas(4, 16), false),
            new Tretja.SluzbenaPot(18, new Cas(4, 17), true),
            new Tretja.SluzbenaPot(44, new Cas(4, 19), true),
            new Tretja.Rekreacija(2, new Cas(4, 22), true),
            new Tretja.Rekreacija(6, new Cas(4, 25), false),
            new Tretja.SluzbenaPot(46, new Cas(4, 33), true),
            new Tretja.SluzbenaPot(28, new Cas(4, 34), true),
            new Tretja.SluzbenaPot(22, new Cas(4, 35), true),
            new Tretja.SluzbenaPot(39, new Cas(4, 35), true),
            new Tretja.Malica(11, new Cas(4, 37), true),
            new Tretja.SluzbenaPot(21, new Cas(4, 37), true),
            new Tretja.SluzbenaPot(30, new Cas(4, 38), false),
            new Tretja.Rekreacija(24, new Cas(4, 46), true),
            new Tretja.SluzbenaPot(1, new Cas(4, 51), false),
            new Tretja.Rekreacija(23, new Cas(4, 51), false),
            new Tretja.Rekreacija(36, new Cas(4, 51), false),
            new Tretja.SluzbenaPot(28, new Cas(4, 58), false),
            new Tretja.SluzbenaPot(1, new Cas(4, 58), true),
            new Tretja.SluzbenaPot(19, new Cas(5, 0), false),
            new Tretja.Rekreacija(6, new Cas(5, 3), true),
            new Tretja.SluzbenaPot(23, new Cas(5, 5), true),
            new Tretja.Rekreacija(0, new Cas(5, 5), false),
            new Tretja.Rekreacija(0, new Cas(5, 9), true),
            new Tretja.Rekreacija(38, new Cas(5, 11), false),
            new Tretja.Malica(43, new Cas(5, 12), false),
            new Tretja.SluzbenaPot(3, new Cas(5, 14), false),
            new Tretja.Rekreacija(49, new Cas(5, 19), false),
            new Tretja.SluzbenaPot(30, new Cas(5, 31), true),
            new Tretja.SluzbenaPot(43, new Cas(5, 38), true),
            new Tretja.Rekreacija(19, new Cas(5, 40), true),
            new Tretja.SluzbenaPot(43, new Cas(5, 43), false),
            new Tretja.Rekreacija(19, new Cas(5, 43), false),
            new Tretja.Malica(49, new Cas(5, 48), true),
            new Tretja.Rekreacija(42, new Cas(5, 50), false),
            new Tretja.SluzbenaPot(22, new Cas(5, 52), false),
            new Tretja.Rekreacija(6, new Cas(5, 58), false),
            new Tretja.Rekreacija(24, new Cas(6, 6), false),
            new Tretja.Malica(12, new Cas(6, 9), false),
            new Tretja.Rekreacija(8, new Cas(6, 14), false),
            new Tretja.SluzbenaPot(39, new Cas(6, 15), false),
            new Tretja.SluzbenaPot(34, new Cas(6, 17), false),
            new Tretja.Malica(10, new Cas(6, 19), false),
            new Tretja.Malica(19, new Cas(6, 20), true),
            new Tretja.SluzbenaPot(1, new Cas(6, 26), false),
            new Tretja.Malica(38, new Cas(6, 30), true),
            new Tretja.SluzbenaPot(12, new Cas(6, 42), true),
            new Tretja.SluzbenaPot(31, new Cas(6, 45), false),
            new Tretja.SluzbenaPot(6, new Cas(6, 47), true),
            new Tretja.SluzbenaPot(20, new Cas(6, 49), false),
            new Tretja.SluzbenaPot(28, new Cas(6, 50), true),
            new Tretja.Rekreacija(3, new Cas(6, 52), true),
            new Tretja.Rekreacija(36, new Cas(6, 53), true),
            new Tretja.SluzbenaPot(6, new Cas(6, 56), false),
            new Tretja.SluzbenaPot(31, new Cas(6, 57), true),
            new Tretja.Rekreacija(43, new Cas(7, 1), true),
            new Tretja.SluzbenaPot(14, new Cas(7, 1), false),
            new Tretja.SluzbenaPot(48, new Cas(7, 13), false),
            new Tretja.Malica(20, new Cas(7, 14), true),
            new Tretja.Malica(19, new Cas(7, 16), false),
            new Tretja.Malica(1, new Cas(7, 16), true),
            new Tretja.Rekreacija(22, new Cas(7, 20), true),
            new Tretja.Rekreacija(42, new Cas(7, 21), true),
            new Tretja.Rekreacija(2, new Cas(7, 31), false),
            new Tretja.Rekreacija(14, new Cas(7, 32), true),
            new Tretja.SluzbenaPot(34, new Cas(7, 37), true),
            new Tretja.Rekreacija(8, new Cas(7, 37), true),
            new Tretja.Malica(24, new Cas(7, 39), true),
            new Tretja.SluzbenaPot(10, new Cas(7, 40), true),
            new Tretja.Rekreacija(8, new Cas(7, 43), false),
            new Tretja.SluzbenaPot(19, new Cas(7, 43), true),
            new Tretja.Rekreacija(45, new Cas(7, 50), false),
            new Tretja.Malica(2, new Cas(7, 51), true),
            new Tretja.SluzbenaPot(44, new Cas(7, 51), false),
            new Tretja.Rekreacija(5, new Cas(8, 0), false),
            new Tretja.SluzbenaPot(26, new Cas(8, 0), false),
            new Tretja.SluzbenaPot(10, new Cas(8, 7), false),
            new Tretja.SluzbenaPot(6, new Cas(8, 11), true),
            new Tretja.Rekreacija(10, new Cas(8, 20), true),
            new Tretja.SluzbenaPot(48, new Cas(8, 21), true),
            new Tretja.Malica(44, new Cas(8, 26), true),
            new Tretja.Rekreacija(45, new Cas(8, 26), true),
            new Tretja.Rekreacija(3, new Cas(8, 30), false),
            new Tretja.Rekreacija(45, new Cas(8, 31), false),
            new Tretja.SluzbenaPot(23, new Cas(8, 32), false),
            new Tretja.SluzbenaPot(45, new Cas(8, 33), true),
            new Tretja.SluzbenaPot(46, new Cas(8, 35), false),
            new Tretja.Rekreacija(23, new Cas(8, 37), true),
            new Tretja.Malica(39, new Cas(8, 38), true),
            new Tretja.Malica(3, new Cas(8, 40), true),
            new Tretja.Rekreacija(0, new Cas(8, 43), false),
            new Tretja.Rekreacija(26, new Cas(8, 51), true),
            new Tretja.Rekreacija(5, new Cas(8, 52), true),
            new Tretja.Rekreacija(47, new Cas(8, 53), false),
            new Tretja.Rekreacija(46, new Cas(8, 55), true),
            new Tretja.Rekreacija(47, new Cas(8, 55), true),
            new Tretja.SluzbenaPot(45, new Cas(9, 2), false),
            new Tretja.Rekreacija(8, new Cas(9, 6), true),
            new Tretja.SluzbenaPot(19, new Cas(9, 8), false),
            new Tretja.Rekreacija(46, new Cas(9, 8), false),
            new Tretja.Rekreacija(14, new Cas(9, 22), false),
            new Tretja.Malica(38, new Cas(9, 27), false),
            new Tretja.SluzbenaPot(30, new Cas(9, 41), false),
            new Tretja.Rekreacija(46, new Cas(9, 48), true),
            new Tretja.Rekreacija(36, new Cas(9, 49), false),
            new Tretja.Rekreacija(26, new Cas(9, 51), false),
            new Tretja.SluzbenaPot(31, new Cas(9, 52), false),
            new Tretja.Malica(45, new Cas(9, 52), true),
            new Tretja.Rekreacija(0, new Cas(9, 54), true),
            new Tretja.Rekreacija(46, new Cas(9, 55), false),
            new Tretja.SluzbenaPot(13, new Cas(10, 12), false),
            new Tretja.SluzbenaPot(36, new Cas(10, 13), true),
            new Tretja.Rekreacija(46, new Cas(10, 32), true),
            new Tretja.Malica(44, new Cas(10, 32), false),
            new Tretja.Malica(30, new Cas(10, 33), true),
            new Tretja.Malica(31, new Cas(10, 36), true),
            new Tretja.Malica(26, new Cas(10, 38), true),
            new Tretja.Malica(14, new Cas(10, 55), true),
            new Tretja.Rekreacija(44, new Cas(10, 58), true),
            new Tretja.Malica(49, new Cas(11, 1), false),
            new Tretja.Malica(3, new Cas(11, 7), false),
            new Tretja.SluzbenaPot(3, new Cas(11, 8), true),
            new Tretja.Rekreacija(19, new Cas(11, 13), true),
            new Tretja.SluzbenaPot(4, new Cas(11, 14), false),
            new Tretja.Rekreacija(0, new Cas(11, 17), false),
            new Tretja.SluzbenaPot(38, new Cas(11, 19), true),
            new Tretja.Rekreacija(13, new Cas(11, 31), true),
            new Tretja.Rekreacija(46, new Cas(11, 38), false),
            new Tretja.SluzbenaPot(3, new Cas(11, 40), false),
            new Tretja.Rekreacija(15, new Cas(11, 50), false),
            new Tretja.SluzbenaPot(36, new Cas(11, 50), false),
            new Tretja.SluzbenaPot(49, new Cas(11, 51), true),
            new Tretja.Rekreacija(46, new Cas(11, 53), true),
            new Tretja.Malica(1, new Cas(11, 53), false),
            new Tretja.Rekreacija(23, new Cas(11, 55), false),
            new Tretja.Rekreacija(0, new Cas(11, 57), true),
            new Tretja.Rekreacija(13, new Cas(11, 58), false),
            new Tretja.Malica(35, new Cas(12, 1), false),
            new Tretja.Malica(36, new Cas(12, 9), true),
            new Tretja.Rekreacija(10, new Cas(12, 9), false),
            new Tretja.SluzbenaPot(35, new Cas(12, 11), true),
            new Tretja.Malica(23, new Cas(12, 17), true),
            new Tretja.SluzbenaPot(38, new Cas(12, 22), false),
            new Tretja.SluzbenaPot(13, new Cas(12, 23), true),
            new Tretja.Rekreacija(4, new Cas(12, 32), true),
            new Tretja.Rekreacija(10, new Cas(12, 40), true),
            new Tretja.SluzbenaPot(15, new Cas(12, 43), true),
            new Tretja.SluzbenaPot(38, new Cas(12, 44), true),
            new Tretja.Malica(26, new Cas(12, 45), false),
            new Tretja.Rekreacija(43, new Cas(12, 48), false),
            new Tretja.Rekreacija(5, new Cas(12, 48), false),
            new Tretja.Rekreacija(26, new Cas(12, 57), true),
            new Tretja.SluzbenaPot(5, new Cas(12, 59), true),
            new Tretja.Rekreacija(43, new Cas(13, 3), true),
            new Tretja.Malica(27, new Cas(13, 4), false),
            new Tretja.Rekreacija(42, new Cas(13, 9), false),
            new Tretja.SluzbenaPot(27, new Cas(13, 15), true),
            new Tretja.Rekreacija(3, new Cas(13, 17), true),
            new Tretja.Malica(42, new Cas(13, 27), true),
            new Tretja.SluzbenaPot(13, new Cas(13, 29), false),
            new Tretja.SluzbenaPot(5, new Cas(13, 30), false),
            new Tretja.Rekreacija(3, new Cas(13, 30), false),
            new Tretja.Malica(13, new Cas(13, 36), true),
            new Tretja.SluzbenaPot(1, new Cas(13, 43), true),
            new Tretja.SluzbenaPot(21, new Cas(13, 48), false),
            new Tretja.SluzbenaPot(27, new Cas(13, 51), false),
            new Tretja.SluzbenaPot(29, new Cas(13, 51), false),
            new Tretja.SluzbenaPot(3, new Cas(14, 9), true),
            new Tretja.Malica(30, new Cas(14, 10), false),
            new Tretja.Rekreacija(30, new Cas(14, 21), true),
            new Tretja.Rekreacija(8, new Cas(14, 29), false),
            new Tretja.Malica(29, new Cas(14, 35), true),
            new Tretja.Rekreacija(5, new Cas(14, 37), true),
            new Tretja.Malica(20, new Cas(14, 38), false),
            new Tretja.SluzbenaPot(27, new Cas(14, 41), true),
            new Tretja.Rekreacija(21, new Cas(14, 43), true),
            new Tretja.SluzbenaPot(1, new Cas(14, 44), false),
            new Tretja.Rekreacija(19, new Cas(14, 45), false),
            new Tretja.SluzbenaPot(38, new Cas(14, 58), false),
            new Tretja.Rekreacija(20, new Cas(15, 2), true),
            new Tretja.Malica(29, new Cas(15, 11), false),
            new Tretja.Rekreacija(4, new Cas(15, 12), false),
            new Tretja.Rekreacija(22, new Cas(15, 13), false),
            new Tretja.Rekreacija(22, new Cas(15, 14), true),
            new Tretja.Rekreacija(19, new Cas(15, 17), true),
            new Tretja.Malica(2, new Cas(15, 18), false),
            new Tretja.Rekreacija(29, new Cas(15, 22), true),
            new Tretja.SluzbenaPot(2, new Cas(15, 25), true),
            new Tretja.Rekreacija(1, new Cas(15, 27), true),
            new Tretja.Rekreacija(29, new Cas(15, 32), false),
            new Tretja.SluzbenaPot(48, new Cas(15, 32), false),
            new Tretja.SluzbenaPot(37, new Cas(15, 37), false),
            new Tretja.Rekreacija(1, new Cas(15, 40), false),
            new Tretja.SluzbenaPot(48, new Cas(15, 41), true),
            new Tretja.Rekreacija(46, new Cas(15, 46), false),
            new Tretja.Malica(16, new Cas(15, 46), false),
            new Tretja.Rekreacija(38, new Cas(15, 51), true),
            new Tretja.Malica(46, new Cas(15, 52), true),
            new Tretja.SluzbenaPot(16, new Cas(15, 52), true),
            new Tretja.Malica(8, new Cas(15, 54), true),
            new Tretja.Rekreacija(4, new Cas(16, 3), true),
            new Tretja.SluzbenaPot(27, new Cas(16, 11), false),
            new Tretja.Malica(32, new Cas(16, 12), false),
            new Tretja.Rekreacija(37, new Cas(16, 13), true),
            new Tretja.Rekreacija(27, new Cas(16, 18), true),
            new Tretja.Rekreacija(41, new Cas(16, 19), false),
            new Tretja.SluzbenaPot(32, new Cas(16, 25), true),
            new Tretja.Rekreacija(0, new Cas(16, 25), false),
            new Tretja.Rekreacija(19, new Cas(16, 26), false),
            new Tretja.SluzbenaPot(6, new Cas(16, 27), false),
            new Tretja.Rekreacija(5, new Cas(16, 29), false),
            new Tretja.SluzbenaPot(16, new Cas(16, 43), false),
            new Tretja.Rekreacija(9, new Cas(16, 49), false),
            new Tretja.Rekreacija(1, new Cas(16, 50), true),
            new Tretja.Rekreacija(38, new Cas(16, 51), false),
            new Tretja.Malica(7, new Cas(17, 4), false),
            new Tretja.Rekreacija(9, new Cas(17, 8), true),
            new Tretja.Malica(5, new Cas(17, 9), true),
            new Tretja.Rekreacija(41, new Cas(17, 17), true),
            new Tretja.SluzbenaPot(2, new Cas(17, 19), false),
            new Tretja.Rekreacija(6, new Cas(17, 19), true),
            new Tretja.Malica(36, new Cas(17, 20), false),
            new Tretja.SluzbenaPot(7, new Cas(17, 30), true),
            new Tretja.Rekreacija(29, new Cas(17, 30), true),
            new Tretja.Malica(33, new Cas(17, 31), false),
            new Tretja.Rekreacija(20, new Cas(17, 32), false),
            new Tretja.Rekreacija(19, new Cas(17, 32), true),
            new Tretja.Rekreacija(33, new Cas(17, 41), true),
            new Tretja.Rekreacija(44, new Cas(17, 43), false),
            new Tretja.SluzbenaPot(32, new Cas(17, 43), false),
            new Tretja.SluzbenaPot(3, new Cas(17, 45), false),
            new Tretja.SluzbenaPot(16, new Cas(17, 47), true),
            new Tretja.Malica(0, new Cas(17, 49), true),
            new Tretja.Rekreacija(32, new Cas(17, 50), true),
            new Tretja.SluzbenaPot(3, new Cas(18, 3), true),
            new Tretja.Rekreacija(6, new Cas(18, 12), false),
            new Tretja.Rekreacija(36, new Cas(18, 15), true),
            new Tretja.Rekreacija(33, new Cas(18, 16), false),
            new Tretja.Rekreacija(29, new Cas(18, 22), false),
            new Tretja.Rekreacija(41, new Cas(18, 39), false),
            new Tretja.Rekreacija(2, new Cas(18, 40), true),
            new Tretja.Rekreacija(32, new Cas(18, 43), false),
            new Tretja.Malica(31, new Cas(18, 46), false),
            new Tretja.Rekreacija(1, new Cas(18, 51), false),
            new Tretja.SluzbenaPot(33, new Cas(18, 51), true),
            new Tretja.SluzbenaPot(31, new Cas(18, 53), true),
            new Tretja.Malica(13, new Cas(18, 53), false),
            new Tretja.Malica(17, new Cas(18, 55), false),
            new Tretja.SluzbenaPot(32, new Cas(18, 57), true),
            new Tretja.SluzbenaPot(38, new Cas(18, 58), true),
            new Tretja.Malica(5, new Cas(19, 2), false),
            new Tretja.SluzbenaPot(1, new Cas(19, 4), true),
            new Tretja.Rekreacija(20, new Cas(19, 5), true),
            new Tretja.Malica(23, new Cas(19, 14), false),
            new Tretja.Malica(45, new Cas(19, 14), false),
            new Tretja.SluzbenaPot(41, new Cas(19, 16), true),
            new Tretja.SluzbenaPot(28, new Cas(19, 18), false),
            new Tretja.Rekreacija(29, new Cas(19, 18), true),
            new Tretja.SluzbenaPot(15, new Cas(19, 18), false),
            new Tretja.Rekreacija(45, new Cas(19, 19), true),
            new Tretja.Rekreacija(9, new Cas(19, 25), false),
            new Tretja.Rekreacija(47, new Cas(19, 26), false),
            new Tretja.Rekreacija(5, new Cas(19, 30), true),
            new Tretja.Rekreacija(36, new Cas(19, 33), false),
            new Tretja.SluzbenaPot(6, new Cas(19, 34), true),
            new Tretja.SluzbenaPot(3, new Cas(19, 36), false),
            new Tretja.Malica(0, new Cas(19, 36), false),
            new Tretja.Rekreacija(37, new Cas(19, 39), false),
            new Tretja.SluzbenaPot(44, new Cas(19, 39), true),
            new Tretja.SluzbenaPot(47, new Cas(19, 43), true),
            new Tretja.SluzbenaPot(18, new Cas(19, 44), false),
            new Tretja.SluzbenaPot(47, new Cas(19, 45), false),
            new Tretja.SluzbenaPot(31, new Cas(19, 51), false),
            new Tretja.SluzbenaPot(13, new Cas(19, 51), true),
            new Tretja.SluzbenaPot(17, new Cas(19, 53), true),
            new Tretja.SluzbenaPot(36, new Cas(19, 53), true),
            new Tretja.SluzbenaPot(28, new Cas(19, 54), true),
            new Tretja.Rekreacija(43, new Cas(19, 56), false),
            new Tretja.SluzbenaPot(6, new Cas(20, 11), false),
            new Tretja.SluzbenaPot(33, new Cas(20, 12), false),
            new Tretja.Rekreacija(23, new Cas(20, 18), true),
            new Tretja.SluzbenaPot(32, new Cas(20, 19), false),
            new Tretja.SluzbenaPot(12, new Cas(20, 23), false),
            new Tretja.Malica(6, new Cas(20, 24), true),
            new Tretja.Rekreacija(30, new Cas(20, 26), false),
            new Tretja.Malica(6, new Cas(20, 28), false),
            new Tretja.Malica(24, new Cas(20, 29), false),
            new Tretja.SluzbenaPot(24, new Cas(20, 31), true),
            new Tretja.SluzbenaPot(7, new Cas(20, 38), false),
            new Tretja.SluzbenaPot(48, new Cas(20, 39), false),
            new Tretja.Rekreacija(22, new Cas(20, 43), false),
            new Tretja.SluzbenaPot(1, new Cas(20, 43), false),
            new Tretja.Rekreacija(9, new Cas(20, 55), true),
            new Tretja.Malica(47, new Cas(20, 56), true),
            new Tretja.SluzbenaPot(49, new Cas(20, 57), false),
            new Tretja.SluzbenaPot(25, new Cas(21, 2), false),
            new Tretja.SluzbenaPot(16, new Cas(21, 9), false),
            new Tretja.SluzbenaPot(17, new Cas(21, 10), false),
            new Tretja.SluzbenaPot(35, new Cas(21, 14), false),
            new Tretja.Malica(8, new Cas(21, 15), false),
            new Tretja.Malica(39, new Cas(21, 27), false),
            new Tretja.Rekreacija(49, new Cas(21, 34), true),
            new Tretja.SluzbenaPot(24, new Cas(21, 36), false),
            new Tretja.SluzbenaPot(44, new Cas(21, 37), false),
            new Tretja.SluzbenaPot(7, new Cas(21, 38), true),
            new Tretja.Rekreacija(29, new Cas(21, 40), false),
            new Tretja.SluzbenaPot(17, new Cas(21, 42), true),
            new Tretja.SluzbenaPot(40, new Cas(21, 44), false),
            new Tretja.SluzbenaPot(13, new Cas(21, 45), false),
            new Tretja.Rekreacija(4, new Cas(21, 50), false),
            new Tretja.SluzbenaPot(43, new Cas(21, 51), true),
            new Tretja.Malica(14, new Cas(21, 51), false),
            new Tretja.SluzbenaPot(7, new Cas(21, 52), false),
            new Tretja.SluzbenaPot(29, new Cas(21, 54), true),
            new Tretja.SluzbenaPot(29, new Cas(21, 55), false),
            new Tretja.Rekreacija(10, new Cas(21, 57), false),
            new Tretja.Malica(47, new Cas(22, 8), false),
            new Tretja.SluzbenaPot(38, new Cas(22, 9), false),
            new Tretja.Rekreacija(21, new Cas(22, 9), false),
            new Tretja.Rekreacija(20, new Cas(22, 18), false),
            new Tretja.Rekreacija(5, new Cas(22, 19), false),
            new Tretja.Malica(25, new Cas(22, 25), true),
            new Tretja.Rekreacija(26, new Cas(22, 27), false),
            new Tretja.SluzbenaPot(36, new Cas(22, 28), false),
            new Tretja.SluzbenaPot(17, new Cas(22, 37), false),
            new Tretja.Rekreacija(2, new Cas(22, 38), false),
            new Tretja.Rekreacija(19, new Cas(22, 45), false),
            new Tretja.Rekreacija(49, new Cas(22, 47), false),
            new Tretja.Malica(11, new Cas(22, 50), false),
            new Tretja.Rekreacija(9, new Cas(23, 7), false),
            new Tretja.SluzbenaPot(28, new Cas(23, 12), false),
            new Tretja.Malica(46, new Cas(23, 16), false),
            new Tretja.Malica(25, new Cas(23, 23), false),
            new Tretja.Rekreacija(27, new Cas(23, 36), false),
            new Tretja.SluzbenaPot(43, new Cas(23, 38), false),
            new Tretja.Rekreacija(45, new Cas(23, 43), false),
            new Tretja.Malica(42, new Cas(23, 45), false),
            new Tretja.SluzbenaPot(41, new Cas(23, 46), false),
            new Tretja.Rekreacija(23, new Cas(23, 52), false),
            new Tretja.SluzbenaPot(34, new Cas(23, 57), false),
        };

        int stZaposlenih = 50;
        Tretja.Dnevnik dnevnik = new Tretja.Dnevnik(stZaposlenih, dogodki);

        List<Cas> casi = new ArrayList<>();
        casi.add(new Cas(0, 50));
        casi.add(new Cas(1, 43));
        casi.add(new Cas(1, 52));
        casi.add(new Cas(2, 36));
        casi.add(new Cas(3, 15));
        casi.add(new Cas(4, 21));
        casi.add(new Cas(5, 38));
        casi.add(new Cas(6, 43));
        casi.add(new Cas(7, 33));
        casi.add(new Cas(8, 15));
        casi.add(new Cas(11, 3));
        casi.add(new Cas(11, 27));
        casi.add(new Cas(11, 56));
        casi.add(new Cas(12, 21));
        casi.add(new Cas(12, 50));
        casi.add(new Cas(12, 56));
        casi.add(new Cas(13, 12));
        casi.add(new Cas(13, 17));
        casi.add(new Cas(13, 40));
        casi.add(new Cas(13, 58));
        casi.add(new Cas(14, 48));
        casi.add(new Cas(14, 56));
        casi.add(new Cas(17, 49));
        casi.add(new Cas(18, 8));
        casi.add(new Cas(19, 14));
        casi.add(new Cas(19, 48));
        casi.add(new Cas(22, 27));
        casi.add(new Cas(22, 42));
        casi.add(new Cas(23, 16));
        casi.add(new Cas(23, 26));

        for (Cas cas: casi) {
            System.out.printf("%s -> %s%n", cas, Arrays.toString(dnevnik.prisotnost(cas)));
        }
    }
}
