
import java.util.*;
import java.util.function.*;

public class Test04 {

    public static void main(String[] args) {
        Comparator<String> comp = (a, b) -> a.compareTo(b);

        List<List<String>> seznami = List.of(
            List.of("adq", "zyeqfznoyvuiqs", "awmhnwfzsqj", "zepuo", "blkow", "ykvuyaonhrtlsomoai", "cqrugmonmkgflgrmamtg", "xaigsq", "dng", "wfqxhnlzaurvsdjrnswp", "ewoowyoh", "vgyvsjdgqhnjmk", "fmhejhrfyhadhtspt", "uufhjrtlchmmgevjmqk", "gervaxrdxnxrbkgurzeo", "uofrzgfhbmyrwjfaxael", "gpfnnhkyplcjnse", "uipqeraca", "gwpulg", "txyxsqwsedlg", "hxigkbbnspahtxffhex", "tncpenywdyalx", "jcikyeuwmhdmxlbkuofl", "sywkcrkf", "jpmdnrpjkwanay", "slcmhtug", "khvanfxn", "sgnrowhj", "kotyzzgklczieja", "seazy", "lfwgkcbp", "rkheyklkoxkdvet", "lvkvt", "rerinksqvobsmnfuir", "mfmzoovhkklqfhlmtivg", "pkkiyhyivjdvchb", "nbkanz", "pbvezuctrg", "oky", "oxzjhzhqkao", "oq", "orlzgoiaqbfbfh", "ort", "olldhrwvdyf", "padiikwyvvngatapnip", "nkzz", "pcbqfheouky", "mpwiprvawo", "qvqgxrpzkhgnajfyqj", "lwnerkwfvwsz", "rigdh", "lhetbhuwrmgysvltlur", "rmicsgjga", "kziih", "sgkip", "kksbeitxcrhqw", "sipmfnvtkpzzyolgq", "juf", "susswy", "jmizwyszpk", "tdnbflcpacfjq", "iloxhdnrqh", "ttjgatlwvoced", "hqyeiywoqqsnklzijxuu", "uimrskwskiderdez", "gwoolsdxwh", "ujihkdexkzag", "gitxnzzgivbxuskarpjm", "uonvfzqioasmytwnmrf", "fqiwq", "vawhpy", "fgifcvwejm", "vjzjzuzedokjccnbmi", "dub", "wvraw", "crvtsaj", "xlycesohubeapzuh", "bpteykme", "yzuijvbcudracw", "bjkhzj", "zuuaeyhxzo", "apmgcndazmmbelwdem", "zzmsicayoogti"),
            List.of("damoacifnhugbnzx", "yioiqvnbwitcly", "dbfnbdw", "pnzu", "lrbyriupzsab", "ilhr", "ughgd", "avojq", "ymvgw"),
            List.of("aeitvoqbyborskyh", "zdxnnbonulpanbzrmtka", "cobvpujpjytygn", "yscxedcjcytntqhb", "dkqsy", "xbvmi", "efjalutifq", "um", "egtdlotquoyxgg", "tugmsxcjkihbodgdtyzk", "fcpinnsfoyslr", "tmunf", "fxsubgiefkgdqjoyudo", "sebewavrsh", "ggrernxh", "sasce", "gpmqr", "qelrrvdlsxjhufpuuk", "ssggmrwyu", "oqdvujbfmllbgcb", "iqqihkgdqjwxp", "ntdncfuzpvvrbww", "jipwgutsvnri", "naqumdafhynhjd", "kdhxoesspaatkcr", "lxowpltw", "liwpenggdasimyqferc", "lnbkxsowypmst", "lnrecuvyyrmalmm", "lerlzbwihtkk", "naaeogpzxioncgrhooj", "judfspnvfdprp", "neaeaqetztkz", "izgtiaocydhoz", "ocetiqoqko", "hrkw", "orwfwrecytqbbehv", "gydzxkwxqpwulewoge", "qzixtmdyo", "gjoxsobxzrluxcfebyx", "sdpvixeplynkqweoq", "fykkmdry", "hlidspg", "fifay", "trugowdpa", "erh", "uezydztngxr", "egmmc", "weaawoxf", "dzgplyzcagzomfhl", "xdgrjuthknbmht", "dcqkdowsctqmbdyvwg", "yuxjwesqgzqgjhojerlo", "ajp", "zjmfrgzr"),
            List.of("alznjylvuasubwf", "yrcfkbypxyipwd", "aovocbuzmkvcbwcdztbp", "xhjxloyu", "cad", "x", "cm", "wpjzssprbolsvej", "dfdimbflo", "tnqda", "dtjacxjqfo", "rrwcroyegjvumd", "dwtwd", "rmslhglxxjtkrz", "etfqoxuhasxvr", "qtirumjb", "evpobcynpfeno", "pzyqiooegeiqakptylxl", "gryqtcquywknemfrq", "pqvdmrsuizinlvgo", "gwifczleeodbwycr", "pn", "hglmiiqsykcvguti", "pghddazccn", "hgrircbkt", "oowxjrxoul", "hhyp", "omcppsiitofu", "hiuxcyadzxnhfsotzyox", "ogzljak", "ifujricksconccilg", "nwsddphfd", "ilfezmkxojc", "novwkjcpfnwmedw", "kyzkrzmcpevshct", "mxhlfaybcu", "lavwbqixabnibp", "mpxytfwzpemcalddobs", "lqtziajlirduno", "mldrlxutz", "ltcrfhlaawsabbohg", "lwnswvjktvzqwvsnzs", "ma", "llnnmgthyvbv", "mtrrrj", "krcjvrug", "pnhidwiklmzcihr", "kpydopzlpkob", "pntheskwijijwb", "ixeusfopzomjvuvz", "qugqhhfnyzxipyef", "itfszht", "saebtqaylehazgnq", "iruyfwd", "vwuinnqhitjj", "ggbvfa", "wjjva", "fpcxsq", "wkxehvejdsyovay", "dspca", "wwnq", "cfsqxmpglrkgmuce", "xfweocpdap", "cfakfijyhqlui", "xtbsniqjeo", "bczvyhevobktju", "zhwopumw", "aacaxh"),
            List.of("asccqhiosx", "tijz", "qdhym", "oxpssvuxymaxnigolsvc", "yfyittxkishqmlstpkb"),
            List.of("zzq", "lrbloryeolwckjk"),
            List.of("aon", "zkhbzxjkc", "byistwdnt", "yisx", "ccucfzfmiwjxpzzl", "yhansuzuikaolstwjnlq", "cr", "wrpaymydrkd", "dhuyevtbtyvdlenj", "uvujzro", "eiqasvenfbpduzqj", "szdqklcnfinnll", "feaoessviodebghcvqu", "shoeivtgbbvoaprxgy", "gtgp", "rgvyanuhqowabrcukvr", "hrxnrbnrzgjbyhltnnl", "rdy", "izdjsxqvq", "qmfothkxvvhc", "kraacwtdqkdjtmxht", "pheizvjyuct", "lrgbgszwlo", "oo", "mtiihmgohzngkavyl", "mvlttwugpco", "ojse", "mbmspaehwrpqkf", "ooyqrvva", "lfjmscgait", "ppoxgqfxtsdnngjlc", "jvuoicljvyuo", "qugqhhfnyzxipyef", "htebgudgabuptsjpvrnz", "refg", "gzmhixnmataxld", "seohiyu", "gfai", "snozyntiazuoidrjztz", "faaoxyoticprumqwlwww", "typgbsj", "dukxt", "uvwdrcvugjsxvdcgip", "cwgftqsfqorjsdnjzcb", "ye", "cpikrrfrtp", "yiqfbsodylp", "bzsdkcpxwer", "zenvgozfuubr", "axhanuh", "zngfgtq"),
            List.of("cxopuvbpidzwbjobiccy", "zehdwh", "lxnfnm", "wqqbytkjgt", "rtj", "tgotphltsgjzwtg", "vzfyenx", "rjpjoelwsnlnsjjnl", "xdpg", "gfbiqeyfyqwta"),
            List.of("aqoxkph", "zhfsriifi", "auue", "xygobd", "dqoixbs", "wohlpecjvxsenfscrq", "dqwn", "vjazarn", "ehksb", "v", "ehocabegigmzvsa", "uycezfgduh", "fq", "scflxiexxwe", "jopsjkew", "rffbnlqwurqrdgnyhut", "ljxolrjh", "qoiwljdlxhbvujr", "oiqlorqrxdmnnodoyzf", "qixsptgdmvbwjti", "phdiepgsfia", "qdyvrwdhknkpelmc", "prudglzhyxtk", "qbr", "qlokwizihyrlvvjqlp", "olocndiws", "riqaicmiba", "nzizubtexdehnlupbgk", "sa", "nbcnhu", "sdhbfasgwslswxnay", "liaofaxz", "utcb", "kretojgl", "vebvkhsne", "kpkofqjolhcpizvqex", "vi", "khxcmtdodakcchyvstyi", "vplpwboppmjbaxpgqbf", "jtezmbvu", "vtegkkijvanupkudkkwy", "jjqbivlvtmidsq", "wrpcztzrwkxbi", "idnyfsklfboe", "yfpyznvyizxmtqrrbho", "hudsjrtvpas", "ylic", "ashvqudmxekkcnd"),
            List.of("acrcqaohsyqmupx", "ypt", "aprzyvmoiherunpak", "wbwhusjhypndsyyvzw", "cerlxclxyglkiwlvxl", "vxglnnethuaoipjz", "crlscqec", "vfenaz", "eyqgnuiitbwin", "lxbqkejlmqmajtpvanpg", "imweqrnoumurgxjntb", "rtmqjyhsnuwfevzdoet", "iragagotrgf", "rjncep", "jmdmcrdrwec", "plf", "jxdah", "mrsl", "spmmmtwjvrbjqf", "kvreu", "oryw", "jpbqss", "qyokxsivcvpjwuvpwbie", "jcatvxeeamgfm", "rmicsgjga", "ioaxatlev", "rxwdkjzftllqnlmyzjt", "fesmkcoinxcvhh", "ttjgatlwvoced", "drrkvk", "vvsnnvd", "cmerxyvexwkgljmjxeu", "vxuh", "aulst", "wcoztvrkontvdcpx", "agqgpscigkcqbqhnrjq", "zcfuenutlj")
        );

        for (List<String> seznam: seznami) {
            System.out.println(Cetrta.alternirajoceMonotono(seznam, comp));
        }
    }
}
