
import java.util.*;

public class Test10 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(26, 29);

        mesto.postavi(18, 25, new Tretja.Poslovna());
        mesto.postavi(14, 25, new Tretja.Poslovna());
        mesto.postavi(5, 2, new Tretja.Stanovanjska(65));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 26, new Tretja.Poslovna());
        mesto.postavi(17, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 3, new Tretja.Stanovanjska(2));
        mesto.postavi(16, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 4, new Tretja.Poslovna());
        mesto.postavi(0, 27, new Tretja.Poslovna());
        mesto.postavi(11, 28, new Tretja.Stanovanjska(19));
        mesto.postavi(8, 16, new Tretja.Stanovanjska(3));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 1, new Tretja.Stanovanjska(20));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 11, new Tretja.Poslovna());
        mesto.postavi(7, 26, new Tretja.Stanovanjska(30));
        mesto.postavi(2, 14, new Tretja.Stanovanjska(54));
        mesto.postavi(14, 23, new Tretja.Stanovanjska(55));
        mesto.postavi(10, 25, new Tretja.Poslovna());
        mesto.postavi(6, 27, new Tretja.Stanovanjska(1));
        mesto.postavi(25, 27, new Tretja.Stanovanjska(33));
        mesto.postavi(20, 14, new Tretja.Poslovna());
        mesto.postavi(2, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 17, new Tretja.Stanovanjska(94));
        mesto.postavi(25, 17, new Tretja.Stanovanjska(27));
        mesto.postavi(2, 14, new Tretja.Poslovna());
        mesto.postavi(21, 28, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 16, new Tretja.Stanovanjska(71));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 25, new Tretja.Poslovna());
        mesto.postavi(1, 28, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 7, new Tretja.Poslovna());
        mesto.postavi(24, 27, new Tretja.Stanovanjska(97));
        mesto.postavi(15, 24, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 13, new Tretja.Stanovanjska(4));
        mesto.postavi(1, 28, new Tretja.Poslovna());
        mesto.postavi(17, 3, new Tretja.Poslovna());
        mesto.postavi(11, 23, new Tretja.Stanovanjska(47));
        mesto.postavi(16, 1, new Tretja.Stanovanjska(79));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 24, new Tretja.Poslovna());
        mesto.postavi(19, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 12, new Tretja.Stanovanjska(3));
        mesto.postavi(24, 24, new Tretja.Poslovna());
        mesto.postavi(8, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 16, new Tretja.Stanovanjska(66));
        mesto.postavi(20, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 12, new Tretja.Stanovanjska(45));
        mesto.postavi(22, 2, new Tretja.Stanovanjska(57));
        mesto.postavi(6, 10, new Tretja.Stanovanjska(99));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 24, new Tretja.Poslovna());
        mesto.postavi(21, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 25, new Tretja.Stanovanjska(21));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 25, new Tretja.Poslovna());
        mesto.postavi(25, 28, new Tretja.Stanovanjska(5));
        mesto.postavi(17, 23, new Tretja.Stanovanjska(23));
        mesto.postavi(10, 6, new Tretja.Stanovanjska(76));
        mesto.postavi(18, 25, new Tretja.Stanovanjska(95));
        mesto.postavi(8, 25, new Tretja.Stanovanjska(96));
        mesto.postavi(1, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 18, new Tretja.Stanovanjska(32));
        mesto.postavi(20, 16, new Tretja.Stanovanjska(81));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 5, new Tretja.Poslovna());
        mesto.postavi(1, 25, new Tretja.Stanovanjska(68));
        mesto.postavi(7, 25, new Tretja.Stanovanjska(89));
        mesto.postavi(20, 18, new Tretja.Stanovanjska(43));
        mesto.postavi(25, 8, new Tretja.Stanovanjska(77));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 28, new Tretja.Stanovanjska(53));
        mesto.postavi(0, 11, new Tretja.Stanovanjska(1));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 17, new Tretja.Stanovanjska(39));
        mesto.postavi(17, 16, new Tretja.Stanovanjska(26));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 13, new Tretja.Stanovanjska(17));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 8, new Tretja.Stanovanjska(98));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 12, new Tretja.Poslovna());
        mesto.postavi(0, 24, new Tretja.Poslovna());
        mesto.postavi(19, 27, new Tretja.Stanovanjska(88));
        mesto.postavi(25, 11, new Tretja.Stanovanjska(48));
        mesto.postavi(12, 12, new Tretja.Stanovanjska(78));
        mesto.postavi(0, 5, new Tretja.Stanovanjska(97));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 11, new Tretja.Poslovna());
        mesto.postavi(19, 7, new Tretja.Poslovna());
        mesto.postavi(25, 18, new Tretja.Stanovanjska(26));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 19, new Tretja.Poslovna());
        mesto.postavi(14, 16, new Tretja.Stanovanjska(20));
        mesto.postavi(11, 0, new Tretja.Poslovna());
        mesto.postavi(21, 10, new Tretja.Stanovanjska(47));
        mesto.postavi(11, 14, new Tretja.Poslovna());
        mesto.postavi(21, 27, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 21, new Tretja.Poslovna());
        mesto.postavi(5, 17, new Tretja.Poslovna());
        mesto.postavi(2, 22, new Tretja.Poslovna());
        mesto.postavi(16, 9, new Tretja.Stanovanjska(59));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 23, new Tretja.Poslovna());
        mesto.postavi(20, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 5, new Tretja.Stanovanjska(16));
        mesto.postavi(20, 16, new Tretja.Poslovna());
        mesto.postavi(11, 4, new Tretja.Stanovanjska(26));
        mesto.postavi(11, 20, new Tretja.Poslovna());
        mesto.postavi(12, 0, new Tretja.Stanovanjska(61));
        mesto.postavi(22, 22, new Tretja.Stanovanjska(79));
        mesto.postavi(17, 16, new Tretja.Stanovanjska(39));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 7, new Tretja.Poslovna());
        mesto.postavi(11, 4, new Tretja.Poslovna());
        mesto.postavi(23, 28, new Tretja.Stanovanjska(25));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 18, new Tretja.Poslovna());
        mesto.postavi(7, 28, new Tretja.Stanovanjska(83));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 15, new Tretja.Stanovanjska(33));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 13, new Tretja.Stanovanjska(74));
        mesto.postavi(6, 25, new Tretja.Poslovna());
        mesto.postavi(15, 3, new Tretja.Poslovna());
        mesto.postavi(24, 19, new Tretja.Poslovna());
        mesto.postavi(1, 2, new Tretja.Stanovanjska(66));
        mesto.postavi(6, 18, new Tretja.Poslovna());
        mesto.postavi(11, 4, new Tretja.Stanovanjska(35));
        mesto.postavi(5, 21, new Tretja.Stanovanjska(27));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 16, new Tretja.Stanovanjska(5));
        mesto.postavi(1, 27, new Tretja.Stanovanjska(39));
        mesto.postavi(5, 26, new Tretja.Stanovanjska(64));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 24, new Tretja.Poslovna());
        mesto.postavi(24, 8, new Tretja.Stanovanjska(59));
        mesto.postavi(11, 12, new Tretja.Stanovanjska(67));
        mesto.postavi(1, 15, new Tretja.Stanovanjska(2));
        mesto.postavi(4, 27, new Tretja.Poslovna());
        mesto.postavi(24, 10, new Tretja.Poslovna());
        mesto.postavi(20, 17, new Tretja.Poslovna());
        mesto.postavi(18, 8, new Tretja.Stanovanjska(93));
        mesto.postavi(6, 4, new Tretja.Stanovanjska(85));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 5, new Tretja.Poslovna());
        mesto.postavi(23, 28, new Tretja.Stanovanjska(47));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 1, new Tretja.Stanovanjska(77));
        mesto.postavi(11, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 8, new Tretja.Poslovna());
        mesto.postavi(1, 24, new Tretja.Stanovanjska(41));
        mesto.postavi(0, 10, new Tretja.Stanovanjska(10));
        mesto.postavi(15, 22, new Tretja.Poslovna());
        mesto.postavi(18, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 23, new Tretja.Stanovanjska(42));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 28, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 0, new Tretja.Poslovna());
        mesto.postavi(19, 13, new Tretja.Stanovanjska(44));
        mesto.postavi(11, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 12, new Tretja.Stanovanjska(89));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 26, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 20, new Tretja.Poslovna());
        mesto.postavi(13, 9, new Tretja.Stanovanjska(66));
        mesto.postavi(17, 7, new Tretja.Stanovanjska(2));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 18, new Tretja.Poslovna());
        mesto.postavi(21, 12, new Tretja.Stanovanjska(18));
        mesto.postavi(22, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 13, new Tretja.Stanovanjska(72));
        mesto.postavi(5, 1, new Tretja.Stanovanjska(64));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 17, new Tretja.Stanovanjska(33));
        mesto.postavi(13, 16, new Tretja.Stanovanjska(69));
        mesto.postavi(12, 26, new Tretja.Stanovanjska(36));
        mesto.postavi(14, 6, new Tretja.Poslovna());
        mesto.postavi(21, 4, new Tretja.Poslovna());
        mesto.postavi(9, 15, new Tretja.Stanovanjska(72));
        mesto.postavi(7, 21, new Tretja.Poslovna());
        mesto.postavi(0, 24, new Tretja.Poslovna());
        mesto.postavi(21, 16, new Tretja.Stanovanjska(66));
        mesto.postavi(1, 21, new Tretja.Poslovna());
        mesto.postavi(20, 23, new Tretja.Stanovanjska(84));
        mesto.postavi(1, 17, new Tretja.Stanovanjska(88));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 24, new Tretja.Poslovna());
        mesto.postavi(6, 17, new Tretja.Poslovna());
        mesto.postavi(23, 9, new Tretja.Stanovanjska(22));
        mesto.postavi(17, 11, new Tretja.Stanovanjska(79));
        mesto.postavi(23, 0, new Tretja.Stanovanjska(11));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 6, new Tretja.Stanovanjska(44));
        mesto.postavi(4, 4, new Tretja.Stanovanjska(4));
        mesto.postavi(1, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 17, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 8, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 7, new Tretja.Poslovna());
        mesto.postavi(11, 15, new Tretja.Poslovna());
        mesto.postavi(2, 9, new Tretja.Stanovanjska(36));
        mesto.postavi(9, 19, new Tretja.Stanovanjska(81));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 22, new Tretja.Stanovanjska(97));
        mesto.postavi(14, 12, new Tretja.Stanovanjska(16));
        mesto.postavi(9, 26, new Tretja.Poslovna());
        mesto.postavi(5, 19, new Tretja.Stanovanjska(73));
        mesto.postavi(12, 5, new Tretja.Poslovna());
        mesto.postavi(10, 19, new Tretja.Stanovanjska(69));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 17, new Tretja.Stanovanjska(15));
        mesto.postavi(1, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 7, new Tretja.Stanovanjska(4));
        mesto.postavi(8, 25, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 4, new Tretja.Poslovna());
        mesto.postavi(10, 22, new Tretja.Poslovna());
        mesto.postavi(3, 25, new Tretja.Stanovanjska(17));
        mesto.postavi(10, 10, new Tretja.Poslovna());
        mesto.postavi(17, 26, new Tretja.Poslovna());
        mesto.postavi(2, 9, new Tretja.Stanovanjska(90));
        mesto.postavi(4, 18, new Tretja.Stanovanjska(92));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 13, new Tretja.Stanovanjska(63));
        mesto.postavi(19, 25, new Tretja.Poslovna());
        mesto.postavi(22, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 20, new Tretja.Stanovanjska(96));
        mesto.postavi(0, 4, new Tretja.Stanovanjska(86));
        mesto.postavi(25, 17, new Tretja.Poslovna());
        mesto.postavi(7, 2, new Tretja.Poslovna());
        mesto.postavi(19, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 25, new Tretja.Poslovna());
        mesto.postavi(16, 26, new Tretja.Poslovna());
        mesto.postavi(12, 26, new Tretja.Poslovna());
        mesto.postavi(9, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 24, new Tretja.Poslovna());
        mesto.postavi(2, 3, new Tretja.Stanovanjska(87));
        mesto.postavi(15, 8, new Tretja.Stanovanjska(92));
        mesto.postavi(5, 24, new Tretja.Stanovanjska(33));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 22, new Tretja.Stanovanjska(37));
        mesto.postavi(1, 26, new Tretja.Stanovanjska(56));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 1, new Tretja.Stanovanjska(29));
        mesto.postavi(5, 28, new Tretja.Stanovanjska(39));
        mesto.postavi(18, 4, new Tretja.Stanovanjska(90));
        mesto.postavi(19, 16, new Tretja.Stanovanjska(39));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        mesto.postavi(15, 11, new Tretja.Poslovna());
        mesto.postavi(3, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 26, new Tretja.Poslovna());
        mesto.postavi(23, 28, new Tretja.Poslovna());
        mesto.postavi(21, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 26, new Tretja.Poslovna());
        mesto.postavi(20, 28, new Tretja.Poslovna());
        mesto.postavi(13, 3, new Tretja.Stanovanjska(27));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 7, new Tretja.Stanovanjska(61));
        mesto.postavi(24, 22, new Tretja.Stanovanjska(42));
        mesto.postavi(10, 24, new Tretja.Stanovanjska(9));
        mesto.postavi(13, 3, new Tretja.Stanovanjska(24));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 24, new Tretja.Stanovanjska(12));
        mesto.postavi(4, 14, new Tretja.Stanovanjska(83));
        mesto.postavi(25, 14, new Tretja.Poslovna());
        mesto.postavi(20, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 21, new Tretja.Poslovna());
        mesto.postavi(0, 12, new Tretja.Stanovanjska(69));
        mesto.postavi(13, 19, new Tretja.Stanovanjska(46));
        mesto.postavi(1, 15, new Tretja.Poslovna());
        mesto.postavi(12, 17, new Tretja.Stanovanjska(3));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 19, new Tretja.Stanovanjska(53));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 17, new Tretja.Poslovna());
        mesto.postavi(17, 1, new Tretja.Poslovna());
        mesto.postavi(21, 5, new Tretja.Stanovanjska(62));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 20, new Tretja.Poslovna());
        mesto.postavi(15, 3, new Tretja.Stanovanjska(80));
        mesto.postavi(1, 9, new Tretja.Stanovanjska(64));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 21, new Tretja.Poslovna());
        mesto.postavi(20, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 13, new Tretja.Poslovna());
        mesto.postavi(24, 21, new Tretja.Poslovna());
        mesto.postavi(12, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 9, new Tretja.Stanovanjska(92));
        mesto.postavi(10, 10, new Tretja.Poslovna());
        mesto.postavi(23, 23, new Tretja.Stanovanjska(76));
        mesto.postavi(21, 11, new Tretja.Poslovna());
        mesto.postavi(14, 26, new Tretja.Poslovna());
        mesto.postavi(10, 25, new Tretja.Stanovanjska(59));
        mesto.postavi(9, 7, new Tretja.Poslovna());
        mesto.postavi(7, 15, new Tretja.Stanovanjska(77));
        mesto.postavi(25, 3, new Tretja.Stanovanjska(31));
        mesto.postavi(4, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 27, new Tretja.Poslovna());
        mesto.postavi(4, 27, new Tretja.Stanovanjska(25));
        mesto.postavi(19, 8, new Tretja.Poslovna());
        mesto.postavi(5, 7, new Tretja.Stanovanjska(74));
        mesto.postavi(2, 17, new Tretja.Poslovna());
        mesto.postavi(10, 20, new Tretja.Poslovna());
        mesto.postavi(13, 27, new Tretja.Poslovna());
        mesto.postavi(24, 1, new Tretja.Poslovna());
        mesto.postavi(15, 22, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 13, new Tretja.Poslovna());
        mesto.postavi(18, 26, new Tretja.Stanovanjska(86));
        mesto.postavi(11, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 25, new Tretja.Poslovna());
        mesto.postavi(21, 7, new Tretja.Stanovanjska(67));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 24, new Tretja.Stanovanjska(33));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 28, new Tretja.Stanovanjska(90));
        mesto.postavi(12, 21, new Tretja.Poslovna());
        mesto.postavi(22, 13, new Tretja.Poslovna());
        mesto.postavi(8, 16, new Tretja.Stanovanjska(83));
        mesto.postavi(25, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 4, new Tretja.Poslovna());
        mesto.postavi(9, 15, new Tretja.Poslovna());
        mesto.postavi(13, 9, new Tretja.Poslovna());
        mesto.postavi(8, 8, new Tretja.Stanovanjska(70));
        mesto.postavi(18, 19, new Tretja.Stanovanjska(87));
        mesto.postavi(24, 20, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 26, new Tretja.Stanovanjska(49));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 21, new Tretja.Poslovna());
        mesto.postavi(12, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 26, new Tretja.Poslovna());
        mesto.postavi(5, 7, new Tretja.Stanovanjska(57));
        mesto.postavi(11, 8, new Tretja.Stanovanjska(84));
        mesto.postavi(13, 3, new Tretja.Poslovna());
        mesto.postavi(6, 8, new Tretja.Poslovna());
        mesto.postavi(8, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 18, new Tretja.Stanovanjska(49));
        mesto.postavi(24, 4, new Tretja.Poslovna());
        mesto.postavi(22, 17, new Tretja.Poslovna());
        mesto.postavi(3, 12, new Tretja.Stanovanjska(95));
        mesto.postavi(11, 15, new Tretja.Stanovanjska(56));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 15, new Tretja.Poslovna());
        mesto.postavi(11, 24, new Tretja.Stanovanjska(49));
        mesto.postavi(23, 10, new Tretja.Stanovanjska(69));
        mesto.postavi(1, 2, new Tretja.Stanovanjska(81));
        mesto.postavi(6, 0, new Tretja.Poslovna());
        mesto.postavi(11, 9, new Tretja.Stanovanjska(16));
        mesto.postavi(20, 27, new Tretja.Stanovanjska(21));
        mesto.postavi(3, 2, new Tretja.Stanovanjska(57));
        mesto.postavi(5, 26, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 21, new Tretja.Poslovna());
        mesto.postavi(18, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 6, new Tretja.Stanovanjska(70));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 19, new Tretja.Poslovna());
        mesto.postavi(19, 25, new Tretja.Poslovna());
        mesto.postavi(0, 17, new Tretja.Poslovna());
        mesto.postavi(25, 14, new Tretja.Stanovanjska(4));
        mesto.postavi(17, 17, new Tretja.Stanovanjska(5));
        mesto.postavi(22, 10, new Tretja.Poslovna());
        mesto.postavi(22, 15, new Tretja.Stanovanjska(14));
        mesto.postavi(21, 28, new Tretja.Stanovanjska(57));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 26, new Tretja.Stanovanjska(22));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 17, new Tretja.Stanovanjska(94));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 20, new Tretja.Poslovna());
        mesto.postavi(2, 22, new Tretja.Stanovanjska(75));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 19, new Tretja.Stanovanjska(41));
        mesto.postavi(12, 5, new Tretja.Stanovanjska(2));
        mesto.postavi(6, 4, new Tretja.Stanovanjska(32));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 15, new Tretja.Poslovna());
        mesto.postavi(8, 23, new Tretja.Poslovna());
        mesto.postavi(9, 3, new Tretja.Stanovanjska(78));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 6, new Tretja.Stanovanjska(58));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 4, new Tretja.Stanovanjska(77));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 15, new Tretja.Stanovanjska(1));
        mesto.postavi(7, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 14, new Tretja.Stanovanjska(61));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 9, new Tretja.Stanovanjska(90));
        mesto.postavi(23, 21, new Tretja.Poslovna());
        mesto.postavi(21, 2, new Tretja.Stanovanjska(85));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 19, new Tretja.Stanovanjska(34));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 7, new Tretja.Stanovanjska(44));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 18, new Tretja.Stanovanjska(45));
        mesto.postavi(11, 28, new Tretja.Poslovna());
        mesto.postavi(10, 4, new Tretja.Stanovanjska(30));
        mesto.postavi(14, 25, new Tretja.Poslovna());
        mesto.postavi(14, 18, new Tretja.Stanovanjska(27));
        mesto.postavi(9, 0, new Tretja.Stanovanjska(30));
        mesto.postavi(19, 0, new Tretja.Poslovna());
        mesto.postavi(1, 28, new Tretja.Poslovna());
        mesto.postavi(3, 3, new Tretja.Stanovanjska(81));
        mesto.postavi(24, 4, new Tretja.Poslovna());
        mesto.postavi(6, 5, new Tretja.Stanovanjska(51));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 20, new Tretja.Stanovanjska(29));
        mesto.postavi(10, 27, new Tretja.Poslovna());
        mesto.postavi(18, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 28, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 16, new Tretja.Stanovanjska(84));
        mesto.postavi(23, 21, new Tretja.Poslovna());
        mesto.postavi(18, 10, new Tretja.Stanovanjska(79));
        mesto.postavi(25, 21, new Tretja.Stanovanjska(48));
        mesto.postavi(2, 28, new Tretja.Stanovanjska(63));
        mesto.postavi(10, 14, new Tretja.Stanovanjska(34));
        mesto.postavi(14, 8, new Tretja.Poslovna());
        mesto.postavi(4, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 26, new Tretja.Stanovanjska(36));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 22, new Tretja.Poslovna());
        mesto.postavi(24, 10, new Tretja.Poslovna());
        mesto.postavi(17, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 24, new Tretja.Stanovanjska(63));
        mesto.postavi(6, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 22, new Tretja.Stanovanjska(96));
        mesto.postavi(19, 5, new Tretja.Stanovanjska(75));
        mesto.postavi(19, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 26, new Tretja.Poslovna());
        mesto.postavi(7, 17, new Tretja.Stanovanjska(56));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 26, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 17, new Tretja.Poslovna());
        mesto.postavi(2, 17, new Tretja.Poslovna());
        mesto.postavi(15, 24, new Tretja.Stanovanjska(68));
        mesto.postavi(12, 18, new Tretja.Stanovanjska(20));
        mesto.postavi(20, 23, new Tretja.Poslovna());
        mesto.postavi(14, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 20, new Tretja.Stanovanjska(76));
        mesto.postavi(7, 21, new Tretja.Stanovanjska(20));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 2, new Tretja.Stanovanjska(12));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 8, new Tretja.Poslovna());
        mesto.postavi(7, 16, new Tretja.Stanovanjska(84));
        mesto.postavi(2, 7, new Tretja.Stanovanjska(58));
        mesto.postavi(1, 10, new Tretja.Poslovna());
        mesto.postavi(19, 16, new Tretja.Poslovna());
        mesto.postavi(0, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 24, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 22, new Tretja.Stanovanjska(36));
        mesto.postavi(20, 26, new Tretja.Stanovanjska(40));
        mesto.postavi(5, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 28, new Tretja.Stanovanjska(53));
        mesto.postavi(12, 18, new Tretja.Poslovna());
        mesto.postavi(7, 25, new Tretja.Stanovanjska(55));
        mesto.postavi(11, 20, new Tretja.Poslovna());
        mesto.postavi(11, 17, new Tretja.Stanovanjska(92));
        mesto.postavi(17, 17, new Tretja.Poslovna());
        mesto.postavi(24, 7, new Tretja.Poslovna());
        mesto.postavi(14, 26, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 26, new Tretja.Poslovna());
        mesto.postavi(23, 11, new Tretja.Stanovanjska(76));
        mesto.postavi(24, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 0, new Tretja.Stanovanjska(80));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 8, new Tretja.Poslovna());
        mesto.postavi(9, 13, new Tretja.Poslovna());
        mesto.postavi(2, 0, new Tretja.Stanovanjska(80));
        mesto.postavi(19, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 8, new Tretja.Poslovna());
        mesto.postavi(4, 20, new Tretja.Stanovanjska(26));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 8, new Tretja.Stanovanjska(12));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 4, new Tretja.Stanovanjska(24));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 11, new Tretja.Stanovanjska(30));
        mesto.postavi(2, 0, new Tretja.Poslovna());
        mesto.postavi(18, 26, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 4, new Tretja.Stanovanjska(61));
        mesto.postavi(16, 26, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 8, new Tretja.Poslovna());
        mesto.postavi(7, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 8, new Tretja.Stanovanjska(46));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 7, new Tretja.Stanovanjska(75));
        mesto.postavi(19, 25, new Tretja.Poslovna());
        mesto.postavi(11, 22, new Tretja.Stanovanjska(42));
        mesto.postavi(11, 17, new Tretja.Stanovanjska(92));
        mesto.postavi(18, 18, new Tretja.Stanovanjska(40));
        mesto.postavi(5, 0, new Tretja.Poslovna());
        mesto.postavi(24, 17, new Tretja.Stanovanjska(35));
        mesto.postavi(22, 8, new Tretja.Stanovanjska(87));
        mesto.postavi(1, 18, new Tretja.Poslovna());
        mesto.postavi(15, 11, new Tretja.Stanovanjska(55));
        mesto.postavi(2, 22, new Tretja.Stanovanjska(47));
        mesto.postavi(13, 17, new Tretja.Poslovna());
        mesto.postavi(25, 22, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 27, new Tretja.Stanovanjska(40));
        mesto.postavi(18, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 15, new Tretja.Stanovanjska(86));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 11, new Tretja.Stanovanjska(58));
        mesto.postavi(22, 11, new Tretja.Stanovanjska(97));
        mesto.postavi(19, 9, new Tretja.Poslovna());
        mesto.postavi(3, 13, new Tretja.Stanovanjska(13));
        mesto.postavi(17, 17, new Tretja.Stanovanjska(94));
        mesto.postavi(18, 5, new Tretja.Stanovanjska(94));
        mesto.postavi(22, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 13, new Tretja.Poslovna());
        mesto.postavi(23, 0, new Tretja.Stanovanjska(57));
        mesto.postavi(21, 28, new Tretja.Poslovna());
        mesto.postavi(12, 3, new Tretja.Poslovna());
        mesto.postavi(14, 8, new Tretja.Stanovanjska(98));
        mesto.postavi(21, 19, new Tretja.Poslovna());
        mesto.postavi(2, 0, new Tretja.Stanovanjska(58));
        mesto.postavi(19, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 1, new Tretja.Stanovanjska(64));
        mesto.postavi(2, 23, new Tretja.Stanovanjska(62));
        mesto.postavi(9, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 17, new Tretja.Poslovna());
        mesto.postavi(3, 28, new Tretja.Poslovna());
        mesto.postavi(7, 13, new Tretja.Stanovanjska(3));
        mesto.postavi(0, 19, new Tretja.Stanovanjska(48));
        mesto.postavi(22, 6, new Tretja.Stanovanjska(3));
        mesto.postavi(24, 25, new Tretja.Stanovanjska(67));
        mesto.postavi(23, 0, new Tretja.Stanovanjska(37));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 0, new Tretja.Poslovna());
        mesto.postavi(0, 8, new Tretja.Stanovanjska(6));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 24, new Tretja.Stanovanjska(73));
        mesto.postavi(8, 10, new Tretja.Stanovanjska(90));
        mesto.postavi(17, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 3, new Tretja.Poslovna());
        mesto.postavi(13, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 21, new Tretja.Poslovna());
        mesto.postavi(22, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
