
import java.util.*;

public class Test07 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(21, 26);

        mesto.postavi(20, 18, new Tretja.Stanovanjska(48));
        mesto.postavi(18, 15, new Tretja.Stanovanjska(74));
        mesto.postavi(12, 7, new Tretja.Stanovanjska(69));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 21, new Tretja.Poslovna());
        mesto.postavi(17, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 17, new Tretja.Poslovna());
        mesto.postavi(13, 10, new Tretja.Poslovna());
        mesto.postavi(3, 16, new Tretja.Stanovanjska(46));
        mesto.postavi(10, 14, new Tretja.Stanovanjska(52));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 16, new Tretja.Poslovna());
        mesto.postavi(1, 22, new Tretja.Stanovanjska(81));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 2, new Tretja.Poslovna());
        mesto.postavi(2, 1, new Tretja.Stanovanjska(31));
        mesto.postavi(18, 12, new Tretja.Stanovanjska(50));
        mesto.postavi(11, 10, new Tretja.Stanovanjska(83));
        mesto.postavi(18, 17, new Tretja.Stanovanjska(49));
        mesto.postavi(18, 0, new Tretja.Poslovna());
        mesto.postavi(20, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 14, new Tretja.Stanovanjska(9));
        mesto.postavi(19, 1, new Tretja.Stanovanjska(8));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 22, new Tretja.Poslovna());
        mesto.postavi(20, 2, new Tretja.Poslovna());
        mesto.postavi(0, 4, new Tretja.Poslovna());
        mesto.postavi(16, 13, new Tretja.Poslovna());
        mesto.postavi(11, 21, new Tretja.Poslovna());
        mesto.postavi(7, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 16, new Tretja.Poslovna());
        mesto.postavi(13, 21, new Tretja.Stanovanjska(1));
        mesto.postavi(10, 20, new Tretja.Poslovna());
        mesto.postavi(14, 23, new Tretja.Stanovanjska(1));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 22, new Tretja.Stanovanjska(71));
        mesto.postavi(3, 22, new Tretja.Poslovna());
        mesto.postavi(9, 8, new Tretja.Stanovanjska(80));
        mesto.postavi(17, 21, new Tretja.Stanovanjska(78));
        mesto.postavi(5, 4, new Tretja.Stanovanjska(93));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 7, new Tretja.Poslovna());
        mesto.postavi(13, 1, new Tretja.Stanovanjska(57));
        mesto.postavi(6, 12, new Tretja.Poslovna());
        mesto.postavi(18, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 15, new Tretja.Poslovna());
        mesto.postavi(17, 6, new Tretja.Stanovanjska(40));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 23, new Tretja.Stanovanjska(25));
        mesto.postavi(13, 4, new Tretja.Stanovanjska(91));
        mesto.postavi(3, 7, new Tretja.Poslovna());
        mesto.postavi(19, 15, new Tretja.Stanovanjska(95));
        mesto.postavi(6, 18, new Tretja.Stanovanjska(23));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 13, new Tretja.Stanovanjska(36));
        mesto.postavi(7, 17, new Tretja.Stanovanjska(46));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 18, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 20, new Tretja.Stanovanjska(3));
        mesto.postavi(19, 24, new Tretja.Poslovna());
        mesto.postavi(19, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 15, new Tretja.Stanovanjska(57));
        mesto.postavi(9, 18, new Tretja.Stanovanjska(13));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 13, new Tretja.Poslovna());
        mesto.postavi(9, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 21, new Tretja.Poslovna());
        mesto.postavi(7, 4, new Tretja.Stanovanjska(100));
        mesto.postavi(13, 19, new Tretja.Stanovanjska(14));
        mesto.postavi(11, 22, new Tretja.Poslovna());
        mesto.postavi(20, 13, new Tretja.Poslovna());
        mesto.postavi(9, 25, new Tretja.Stanovanjska(78));
        mesto.postavi(5, 25, new Tretja.Stanovanjska(35));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 1, new Tretja.Stanovanjska(20));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 20, new Tretja.Stanovanjska(56));
        mesto.postavi(16, 4, new Tretja.Stanovanjska(70));
        mesto.postavi(7, 11, new Tretja.Poslovna());
        mesto.postavi(10, 22, new Tretja.Stanovanjska(21));
        mesto.postavi(0, 15, new Tretja.Poslovna());
        mesto.postavi(14, 7, new Tretja.Stanovanjska(19));
        mesto.postavi(7, 3, new Tretja.Poslovna());
        mesto.postavi(6, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 4, new Tretja.Stanovanjska(27));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 5, new Tretja.Stanovanjska(67));
        mesto.postavi(19, 0, new Tretja.Poslovna());
        mesto.postavi(2, 11, new Tretja.Stanovanjska(83));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 7, new Tretja.Poslovna());
        mesto.postavi(11, 24, new Tretja.Stanovanjska(88));
        mesto.postavi(9, 6, new Tretja.Poslovna());
        mesto.postavi(4, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 20, new Tretja.Poslovna());
        mesto.postavi(15, 22, new Tretja.Stanovanjska(28));
        mesto.postavi(8, 22, new Tretja.Poslovna());
        mesto.postavi(10, 3, new Tretja.Poslovna());
        mesto.postavi(3, 20, new Tretja.Stanovanjska(5));
        mesto.postavi(12, 17, new Tretja.Poslovna());
        mesto.postavi(17, 25, new Tretja.Poslovna());
        mesto.postavi(2, 3, new Tretja.Stanovanjska(19));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 18, new Tretja.Poslovna());
        mesto.postavi(8, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 8, new Tretja.Stanovanjska(64));
        mesto.postavi(6, 10, new Tretja.Stanovanjska(97));
        mesto.postavi(13, 17, new Tretja.Poslovna());
        mesto.postavi(9, 1, new Tretja.Poslovna());
        mesto.postavi(5, 17, new Tretja.Stanovanjska(4));
        mesto.postavi(12, 24, new Tretja.Stanovanjska(93));
        mesto.postavi(5, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 19, new Tretja.Poslovna());
        mesto.postavi(19, 23, new Tretja.Stanovanjska(48));
        mesto.postavi(5, 24, new Tretja.Stanovanjska(41));
        mesto.postavi(12, 13, new Tretja.Stanovanjska(53));
        mesto.postavi(12, 2, new Tretja.Poslovna());
        mesto.postavi(14, 14, new Tretja.Poslovna());
        mesto.postavi(2, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 7, new Tretja.Stanovanjska(87));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 3, new Tretja.Poslovna());
        mesto.postavi(17, 1, new Tretja.Poslovna());
        mesto.postavi(16, 24, new Tretja.Stanovanjska(37));
        mesto.postavi(2, 17, new Tretja.Stanovanjska(31));
        mesto.postavi(13, 24, new Tretja.Poslovna());
        mesto.postavi(11, 6, new Tretja.Poslovna());
        mesto.postavi(3, 12, new Tretja.Stanovanjska(70));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 9, new Tretja.Stanovanjska(45));
        mesto.postavi(12, 20, new Tretja.Poslovna());
        mesto.postavi(9, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 7, new Tretja.Stanovanjska(68));
        mesto.postavi(9, 0, new Tretja.Stanovanjska(63));
        mesto.postavi(13, 16, new Tretja.Stanovanjska(78));
        mesto.postavi(18, 6, new Tretja.Stanovanjska(92));
        mesto.postavi(4, 10, new Tretja.Stanovanjska(46));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 11, new Tretja.Stanovanjska(98));
        mesto.postavi(20, 16, new Tretja.Stanovanjska(69));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 12, new Tretja.Poslovna());
        mesto.postavi(15, 7, new Tretja.Stanovanjska(45));
        mesto.postavi(11, 9, new Tretja.Poslovna());
        mesto.postavi(8, 8, new Tretja.Poslovna());
        mesto.postavi(2, 6, new Tretja.Poslovna());
        mesto.postavi(4, 19, new Tretja.Stanovanjska(34));
        mesto.postavi(19, 3, new Tretja.Stanovanjska(19));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 25, new Tretja.Stanovanjska(63));
        mesto.postavi(15, 4, new Tretja.Stanovanjska(74));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 5, new Tretja.Poslovna());
        mesto.postavi(3, 3, new Tretja.Stanovanjska(63));
        mesto.postavi(2, 9, new Tretja.Stanovanjska(14));
        mesto.postavi(5, 11, new Tretja.Poslovna());
        mesto.postavi(6, 22, new Tretja.Stanovanjska(99));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 13, new Tretja.Poslovna());
        mesto.postavi(13, 20, new Tretja.Poslovna());
        mesto.postavi(13, 12, new Tretja.Stanovanjska(83));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 12, new Tretja.Poslovna());
        mesto.postavi(5, 2, new Tretja.Poslovna());
        mesto.postavi(1, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 15, new Tretja.Poslovna());
        mesto.postavi(10, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 5, new Tretja.Poslovna());
        mesto.postavi(15, 17, new Tretja.Stanovanjska(45));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 13, new Tretja.Stanovanjska(59));
        mesto.postavi(15, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 7, new Tretja.Stanovanjska(99));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 8, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Poslovna());
        mesto.postavi(5, 1, new Tretja.Stanovanjska(75));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 19, new Tretja.Poslovna());
        mesto.postavi(6, 6, new Tretja.Stanovanjska(84));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 5, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Stanovanjska(23));
        mesto.postavi(7, 9, new Tretja.Stanovanjska(85));
        mesto.postavi(4, 6, new Tretja.Poslovna());
        mesto.postavi(20, 8, new Tretja.Poslovna());
        mesto.postavi(17, 3, new Tretja.Stanovanjska(94));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 16, new Tretja.Stanovanjska(13));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 12, new Tretja.Poslovna());
        mesto.postavi(4, 12, new Tretja.Stanovanjska(41));
        mesto.postavi(10, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 18, new Tretja.Stanovanjska(51));
        mesto.postavi(3, 1, new Tretja.Poslovna());
        mesto.postavi(0, 18, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Stanovanjska(66));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 18, new Tretja.Poslovna());
        mesto.postavi(12, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 20, new Tretja.Stanovanjska(70));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 13, new Tretja.Stanovanjska(38));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 13, new Tretja.Stanovanjska(39));
        mesto.postavi(12, 9, new Tretja.Stanovanjska(25));
        mesto.postavi(16, 5, new Tretja.Stanovanjska(19));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 20, new Tretja.Stanovanjska(50));
        mesto.postavi(7, 15, new Tretja.Stanovanjska(53));
        mesto.postavi(16, 12, new Tretja.Poslovna());
        mesto.postavi(12, 11, new Tretja.Stanovanjska(98));
        mesto.postavi(1, 11, new Tretja.Poslovna());
        mesto.postavi(17, 19, new Tretja.Stanovanjska(59));
        mesto.postavi(5, 23, new Tretja.Stanovanjska(19));
        mesto.postavi(17, 22, new Tretja.Stanovanjska(82));
        mesto.postavi(18, 18, new Tretja.Poslovna());
        mesto.postavi(14, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 20, new Tretja.Poslovna());
        mesto.postavi(11, 15, new Tretja.Poslovna());
        mesto.postavi(8, 12, new Tretja.Poslovna());
        mesto.postavi(8, 1, new Tretja.Stanovanjska(84));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 5, new Tretja.Stanovanjska(93));
        mesto.postavi(6, 25, new Tretja.Poslovna());
        mesto.postavi(13, 7, new Tretja.Poslovna());
        mesto.postavi(5, 8, new Tretja.Stanovanjska(81));
        mesto.postavi(18, 21, new Tretja.Poslovna());
        mesto.postavi(1, 4, new Tretja.Poslovna());
        mesto.postavi(19, 13, new Tretja.Stanovanjska(12));
        mesto.postavi(10, 9, new Tretja.Stanovanjska(46));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 4, new Tretja.Stanovanjska(76));
        mesto.postavi(4, 23, new Tretja.Stanovanjska(48));
        mesto.postavi(11, 23, new Tretja.Stanovanjska(13));
        mesto.postavi(10, 24, new Tretja.Stanovanjska(29));
        mesto.postavi(20, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 20, new Tretja.Stanovanjska(59));
        mesto.postavi(0, 2, new Tretja.Poslovna());
        mesto.postavi(0, 3, new Tretja.Stanovanjska(96));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 12, new Tretja.Stanovanjska(84));
        mesto.postavi(9, 23, new Tretja.Poslovna());
        mesto.postavi(5, 22, new Tretja.Stanovanjska(10));
        mesto.postavi(20, 23, new Tretja.Poslovna());
        mesto.postavi(0, 25, new Tretja.Stanovanjska(84));
        mesto.postavi(14, 18, new Tretja.Stanovanjska(17));
        mesto.postavi(9, 16, new Tretja.Poslovna());
        mesto.postavi(3, 17, new Tretja.Stanovanjska(13));
        mesto.postavi(12, 16, new Tretja.Stanovanjska(27));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 8, new Tretja.Poslovna());
        mesto.postavi(15, 6, new Tretja.Stanovanjska(36));
        mesto.postavi(13, 0, new Tretja.Stanovanjska(83));
        mesto.postavi(18, 25, new Tretja.Stanovanjska(80));
        mesto.postavi(2, 21, new Tretja.Poslovna());
        mesto.postavi(14, 2, new Tretja.Stanovanjska(69));
        mesto.postavi(20, 17, new Tretja.Stanovanjska(49));
        mesto.postavi(3, 9, new Tretja.Stanovanjska(71));
        mesto.postavi(9, 20, new Tretja.Stanovanjska(74));
        mesto.postavi(7, 10, new Tretja.Stanovanjska(54));
        mesto.postavi(2, 16, new Tretja.Stanovanjska(49));
        mesto.postavi(9, 19, new Tretja.Stanovanjska(42));
        mesto.postavi(6, 5, new Tretja.Stanovanjska(9));
        mesto.postavi(14, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 2, new Tretja.Stanovanjska(42));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 25, new Tretja.Stanovanjska(40));
        mesto.postavi(16, 19, new Tretja.Stanovanjska(94));
        mesto.postavi(7, 16, new Tretja.Poslovna());
        mesto.postavi(17, 24, new Tretja.Poslovna());
        mesto.postavi(17, 20, new Tretja.Stanovanjska(61));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 8, new Tretja.Poslovna());
        mesto.postavi(6, 20, new Tretja.Poslovna());
        mesto.postavi(9, 11, new Tretja.Stanovanjska(47));
        mesto.postavi(17, 17, new Tretja.Poslovna());
        mesto.postavi(10, 10, new Tretja.Poslovna());
        mesto.postavi(11, 3, new Tretja.Stanovanjska(37));
        mesto.postavi(13, 3, new Tretja.Stanovanjska(84));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 14, new Tretja.Poslovna());
        mesto.postavi(4, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 14, new Tretja.Stanovanjska(32));
        mesto.postavi(2, 25, new Tretja.Stanovanjska(90));
        mesto.postavi(1, 12, new Tretja.Poslovna());
        mesto.postavi(15, 11, new Tretja.Poslovna());
        mesto.postavi(1, 18, new Tretja.Stanovanjska(6));
        mesto.postavi(11, 25, new Tretja.Stanovanjska(43));
        mesto.postavi(13, 23, new Tretja.Stanovanjska(61));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 24, new Tretja.Poslovna());
        mesto.postavi(15, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 1, new Tretja.Stanovanjska(2));
        mesto.postavi(1, 8, new Tretja.Stanovanjska(78));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 3, new Tretja.Stanovanjska(78));
        mesto.postavi(12, 0, new Tretja.Stanovanjska(41));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 19, new Tretja.Poslovna());
        mesto.postavi(6, 19, new Tretja.Poslovna());
        mesto.postavi(12, 25, new Tretja.Stanovanjska(9));
        mesto.postavi(1, 7, new Tretja.Stanovanjska(5));
        mesto.postavi(19, 8, new Tretja.Stanovanjska(7));
        mesto.postavi(15, 9, new Tretja.Poslovna());
        mesto.postavi(18, 4, new Tretja.Poslovna());
        mesto.postavi(19, 25, new Tretja.Poslovna());
        mesto.postavi(7, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 23, new Tretja.Stanovanjska(27));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 6, new Tretja.Stanovanjska(6));
        mesto.postavi(8, 17, new Tretja.Poslovna());
        mesto.postavi(4, 13, new Tretja.Stanovanjska(10));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 12, new Tretja.Stanovanjska(99));
        mesto.postavi(8, 20, new Tretja.Stanovanjska(47));
        mesto.postavi(0, 1, new Tretja.Poslovna());
        mesto.postavi(9, 7, new Tretja.Poslovna());
        mesto.postavi(17, 4, new Tretja.Stanovanjska(96));
        mesto.postavi(3, 21, new Tretja.Poslovna());
        mesto.postavi(14, 8, new Tretja.Poslovna());
        mesto.postavi(18, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 23, new Tretja.Poslovna());
        mesto.postavi(10, 17, new Tretja.Poslovna());
        mesto.postavi(17, 8, new Tretja.Stanovanjska(66));
        mesto.postavi(12, 6, new Tretja.Stanovanjska(83));
        mesto.postavi(20, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 12, new Tretja.Stanovanjska(8));
        mesto.postavi(15, 24, new Tretja.Stanovanjska(30));
        mesto.postavi(4, 5, new Tretja.Stanovanjska(86));
        mesto.postavi(3, 11, new Tretja.Stanovanjska(63));
        mesto.postavi(4, 24, new Tretja.Poslovna());
        mesto.postavi(10, 16, new Tretja.Stanovanjska(45));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 12, new Tretja.Stanovanjska(71));
        mesto.postavi(20, 6, new Tretja.Stanovanjska(88));
        mesto.postavi(19, 11, new Tretja.Stanovanjska(89));
        mesto.postavi(11, 14, new Tretja.Poslovna());
        mesto.postavi(14, 10, new Tretja.Stanovanjska(33));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 25, new Tretja.Stanovanjska(27));
        mesto.postavi(16, 22, new Tretja.Stanovanjska(72));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 11, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 0, new Tretja.Stanovanjska(17));
        mesto.postavi(1, 9, new Tretja.Stanovanjska(97));
        mesto.postavi(16, 2, new Tretja.Poslovna());
        mesto.postavi(4, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 13, new Tretja.Stanovanjska(54));
        mesto.postavi(12, 3, new Tretja.Poslovna());
        mesto.postavi(4, 22, new Tretja.Poslovna());
        mesto.postavi(8, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 2, new Tretja.Stanovanjska(87));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 13, new Tretja.Stanovanjska(1));
        mesto.postavi(19, 17, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 10, new Tretja.Poslovna());
        mesto.postavi(9, 17, new Tretja.Stanovanjska(85));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 18, new Tretja.Poslovna());
        mesto.postavi(0, 23, new Tretja.Poslovna());
        mesto.postavi(10, 6, new Tretja.Poslovna());
        mesto.postavi(7, 7, new Tretja.Stanovanjska(95));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 18, new Tretja.Stanovanjska(99));
        mesto.postavi(16, 1, new Tretja.Poslovna());
        mesto.postavi(9, 4, new Tretja.Poslovna());
        mesto.postavi(3, 24, new Tretja.Stanovanjska(91));
        mesto.postavi(14, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 0, new Tretja.Stanovanjska(47));
        mesto.postavi(11, 0, new Tretja.Poslovna());
        mesto.postavi(8, 21, new Tretja.Stanovanjska(27));
        mesto.postavi(20, 11, new Tretja.Stanovanjska(94));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        mesto.postavi(14, 17, new Tretja.Poslovna());
        mesto.postavi(6, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 24, new Tretja.Stanovanjska(42));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 16, new Tretja.Stanovanjska(83));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 10, new Tretja.Stanovanjska(23));
        mesto.postavi(5, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 14, new Tretja.Stanovanjska(65));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 4, new Tretja.Stanovanjska(12));
        mesto.postavi(9, 21, new Tretja.Stanovanjska(66));
        mesto.postavi(17, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 23, new Tretja.Poslovna());
        mesto.postavi(0, 8, new Tretja.Stanovanjska(57));
        mesto.postavi(17, 10, new Tretja.Stanovanjska(85));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 7, new Tretja.Poslovna());
        mesto.postavi(11, 7, new Tretja.Stanovanjska(32));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 11, new Tretja.Stanovanjska(44));
        mesto.postavi(9, 15, new Tretja.Poslovna());
        mesto.postavi(15, 25, new Tretja.Stanovanjska(16));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 19, new Tretja.Poslovna());
        mesto.postavi(14, 16, new Tretja.Stanovanjska(58));
        mesto.postavi(0, 22, new Tretja.Stanovanjska(50));
        mesto.postavi(1, 14, new Tretja.Poslovna());
        mesto.postavi(4, 8, new Tretja.Stanovanjska(52));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 0, new Tretja.Stanovanjska(44));
        mesto.postavi(13, 22, new Tretja.Poslovna());
        mesto.postavi(11, 17, new Tretja.Stanovanjska(90));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 14, new Tretja.Stanovanjska(70));
        mesto.postavi(2, 19, new Tretja.Poslovna());
        mesto.postavi(4, 14, new Tretja.Stanovanjska(5));
        mesto.postavi(11, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 1, new Tretja.Poslovna());
        mesto.postavi(3, 15, new Tretja.Stanovanjska(3));
        mesto.postavi(20, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 7, new Tretja.Poslovna());
        mesto.postavi(5, 6, new Tretja.Stanovanjska(69));
        mesto.postavi(15, 8, new Tretja.Stanovanjska(28));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 12, new Tretja.Stanovanjska(34));
        mesto.postavi(3, 19, new Tretja.Stanovanjska(36));
        mesto.postavi(12, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 4, new Tretja.Poslovna());
        mesto.postavi(2, 14, new Tretja.Stanovanjska(100));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 13, new Tretja.Poslovna());
        mesto.postavi(18, 10, new Tretja.Stanovanjska(87));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 10, new Tretja.Poslovna());
        mesto.postavi(7, 12, new Tretja.Stanovanjska(22));
        mesto.postavi(18, 24, new Tretja.Stanovanjska(55));
        mesto.postavi(1, 20, new Tretja.Stanovanjska(26));
        mesto.postavi(5, 16, new Tretja.Stanovanjska(22));
        mesto.postavi(0, 24, new Tretja.Poslovna());
        mesto.postavi(13, 15, new Tretja.Stanovanjska(78));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 8, new Tretja.Poslovna());
        mesto.postavi(17, 9, new Tretja.Stanovanjska(54));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 3, new Tretja.Poslovna());
        mesto.postavi(12, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 10, new Tretja.Stanovanjska(31));
        mesto.postavi(16, 7, new Tretja.Stanovanjska(58));
        mesto.postavi(10, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 2, new Tretja.Poslovna());
        mesto.postavi(1, 23, new Tretja.Stanovanjska(5));
        mesto.postavi(12, 22, new Tretja.Stanovanjska(71));
        mesto.postavi(16, 6, new Tretja.Stanovanjska(25));
        mesto.postavi(17, 13, new Tretja.Poslovna());
        mesto.postavi(20, 1, new Tretja.Stanovanjska(33));
        mesto.postavi(20, 9, new Tretja.Poslovna());
        mesto.postavi(8, 15, new Tretja.Stanovanjska(64));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 11, new Tretja.Stanovanjska(29));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 23, new Tretja.Poslovna());
        mesto.postavi(16, 18, new Tretja.Stanovanjska(55));
        mesto.postavi(17, 15, new Tretja.Poslovna());
        mesto.postavi(12, 12, new Tretja.Stanovanjska(32));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 21, new Tretja.Stanovanjska(89));
        mesto.postavi(7, 0, new Tretja.Stanovanjska(50));
        mesto.postavi(7, 14, new Tretja.Stanovanjska(59));
        mesto.postavi(8, 4, new Tretja.Poslovna());
        mesto.postavi(0, 20, new Tretja.Poslovna());
        mesto.postavi(15, 16, new Tretja.Poslovna());
        mesto.postavi(11, 18, new Tretja.Stanovanjska(10));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 3, new Tretja.Stanovanjska(28));
        mesto.postavi(4, 11, new Tretja.Stanovanjska(88));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 0, new Tretja.Stanovanjska(36));
        mesto.postavi(6, 13, new Tretja.Stanovanjska(74));
        mesto.postavi(15, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 14, new Tretja.Poslovna());
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(12, 18, new Tretja.Stanovanjska(86));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 17, new Tretja.Stanovanjska(86));
        mesto.postavi(19, 6, new Tretja.Poslovna());
        mesto.postavi(4, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 0, new Tretja.Stanovanjska(66));
        mesto.postavi(16, 0, new Tretja.Stanovanjska(54));
        mesto.postavi(2, 18, new Tretja.Poslovna());
        mesto.postavi(8, 2, new Tretja.Poslovna());
        mesto.postavi(18, 3, new Tretja.Stanovanjska(100));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 15, new Tretja.Poslovna());
        mesto.postavi(2, 15, new Tretja.Poslovna());
        mesto.postavi(5, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 9, new Tretja.Stanovanjska(80));
        mesto.postavi(16, 9, new Tretja.Stanovanjska(62));
        mesto.postavi(12, 21, new Tretja.Poslovna());
        mesto.postavi(0, 16, new Tretja.Poslovna());
        mesto.postavi(13, 18, new Tretja.Poslovna());
        mesto.postavi(11, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 19, new Tretja.Stanovanjska(26));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 24, new Tretja.Stanovanjska(68));
        mesto.postavi(8, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 9, new Tretja.Stanovanjska(71));
        mesto.postavi(8, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 20, new Tretja.Poslovna());
        mesto.postavi(20, 4, new Tretja.Stanovanjska(34));
        mesto.postavi(17, 16, new Tretja.Stanovanjska(75));
        mesto.postavi(6, 17, new Tretja.Stanovanjska(59));
        mesto.postavi(3, 10, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 1, new Tretja.Poslovna());
        mesto.postavi(15, 14, new Tretja.Stanovanjska(28));
        mesto.postavi(0, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 15, new Tretja.Poslovna());
        mesto.postavi(14, 20, new Tretja.Stanovanjska(69));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 11, new Tretja.Stanovanjska(96));
        mesto.postavi(2, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 22, new Tretja.Poslovna());
        mesto.postavi(1, 16, new Tretja.Stanovanjska(11));
        mesto.postavi(15, 20, new Tretja.Poslovna());
        mesto.postavi(5, 13, new Tretja.Stanovanjska(30));
        mesto.postavi(0, 10, new Tretja.Stanovanjska(62));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 5, new Tretja.Stanovanjska(37));
        mesto.postavi(6, 2, new Tretja.Stanovanjska(58));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 10, new Tretja.Stanovanjska(20));
        mesto.postavi(6, 21, new Tretja.Poslovna());
        mesto.postavi(14, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
    }
}
