
import java.util.Arrays;

public class Test34 {
    public static void main(String[] args) {
        int[] stolpi = {15};

        Tretja.Ukaz[] ukazi = {
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Postavi(0),
            new Tretja.Odvzemi(0),
            new Tretja.Odvzemi(0),
        };

        for (Tretja.Ukaz ukaz: ukazi) {
            ukaz.izvedi(stolpi);
        }
        System.out.println(Arrays.toString(stolpi));
    }
}
